### ISSUE TITLE
Builder: query by key-value pairs

### ISSUE THREAD

**Issue by dholroyd** [yescallop/fluent-uri-rs#13]
I would love to be able to build a query by supplying a series of key-value pairs, and have the builder apply encoding to the keys and values as a browser would when handling a fields in a `<form method="GET">`.

Elsewhere, the `uri_builder` crate has a [`query(&str, &str)` method](https://docs.rs/uri-builder/0.10/uri_builder/struct.URI.html#method.query), but I don't believe it handles the encoding.

Taking the idea further, it would be amazing to be able to supply an implementation of `serde::Serialize` and have that automatically serialised into a query with keys and values encoded.  (But I can appreciate `fluent-uri`  might not want to depend on `serde`, and `Serialize` is significantly more complicated than an HTML form :sweat:.)

**Comment by yescallop** [comment]
Hi, here is an example of building a query string from key-value pairs: https://docs.rs/fluent-uri/0.2.0-alpha.5/fluent_uri/encoding/struct.EString.html#examples

Would you think that the current API meets your specific need?

**Comment by dholroyd** [comment]
Ah, I had missed this example - thank you
