### ISSUE TITLE
publish to crates.io

### ISSUE THREAD

**Issue by IWANABETHATGUY** [yescallop/fluent-uri-rs#2]
It seems this crate is almost completed, but i can't found it in crates.io and doc.rs, or it is called other name than `fluent-uri`?

**Comment by yescallop** [comment]
Haven't published it to crates.io yet. There may be a few things to check before doing that, which I guess won't take too long.

**Comment by yescallop** [comment]
I've just published the first version 0.1.0 to crates.io :)

**Comment by IWANABETHATGUY** [comment]
Thanks a lot!

**Comment by yescallop** [comment]
Ah I just wanted to say after some fuzzing I found several bugs in the previous versions and decided to yank all of them. I think it might take some more time for me to publish a new release that is correct enough.

**Comment by yescallop** [comment]
Published v0.1.3 to crates.io.
