### ISSUE TITLE
add URL

### ISSUE THREAD

**Issue by 89z** [yescallop/fluent-uri-rs#4]
This repo doesn't have the text "URL" in the description, or topics, so this search wont find this repo:

https://github.com/search?q=url+language:rust

also some crates have URL keyword:

https://github.com/servo/rust-url/blob/v2.2.2/url/Cargo.toml#L12

this one does not:

https://github.com/yescallop/fluent-uri-rs/blob/v0.1.3/Cargo.toml#L10

so these will fail too:

- https://crates.io/keywords/url
- https://crates.io/search?q=url

**Comment by yescallop** [comment]
This crate is an implementation of IETF [RFC 3986 - Uniform Resource Identifier (URI): Generic Syntax][1], rather than the WHATWG [URL Standard][2]. You may refer to these specs to see how they differ.

[1]: https://datatracker.ietf.org/doc/html/rfc3986/
[2]: https://url.spec.whatwg.org/

**Comment by 89z** [comment]
OK fair enough, but you're only hurting yourself by not including it. People might search for either term.
