### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by jelacious** [yescallop/fluent-uri-rs#6]
Hiya!

From a quick cursory glance over the API of this crate it looks like it would be possible to support `no_std` without too much trouble, mostly just cfging all `std` uses with either `core` or `alloc`. Is this something you would be interested in? I could of course do so myself but thought I would ask first.

Supporting `no_std` would allow this crate to be more easily used on more under-powered systems and make it a tad-bit smaller when compiling as well, which would be quite handy in my use-case.

**Comment by yescallop** [comment]
It would be great for this crate to support `no_std`, but as `Ip{v4, v6}Addr` requires `std` we would need to decide what to exclude when `std` is gone. Any ideas?

**Comment by jelacious** [comment]
There are a few different options depending on how much of the `std::net` functionality you want to retain.

I think just using [no-std-net](https://lib.rs/crates/no-std-net) as a simple drop-in replacement could suffice, but that repo seems to be a bit stale. It does however implement all the stuff you would need. There seems to have been some [discussion]( https://github.com/rust-lang/rust/issues/27709#issuecomment-154461291) on if the `net` stuff should be used in `core` that just petered off.

[smoltcp's](https://github.com/smoltcp-rs/smoltcp) solution to this was to implement their own quite thorough IP types:
* [IpAddress Enum](https://github.com/smoltcp-rs/smoltcp/blob/master/src/wire/ip.rs)
* [v4 definition](https://github.com/smoltcp-rs/smoltcp/blob/master/src/wire/ipv4.rs)
* [v6 definition](https://github.com/smoltcp-rs/smoltcp/blob/master/src/wire/ipv6.rs)

You could also go the nuclear option like [r-efi](https://docs.rs/r-efi/latest/src/r_efi/base.rs.html#481-485) and have a very small IP Address implementation, but that might be too limiting.

I think from a perspective of minimizing the amount of dependencies something like what smoltcp has done would be preferable. Since the code is 0BSD licensed and actively maintained one could just copy that code into this project and replace everything related to `std::net` with that.
